/*
 * Open Legal Data API
 * With the Open Legal Data API you can access various data from the legal domain, e.g. law text or case files. The data may be used for semantic analysis or to create statistics. For more information visit our website. https://openlegaldata.io/
 *
 * OpenAPI spec version: v1
 * Contact: hello@openlegaldata.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * CaseSearch
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-18T15:11:46.584Z")
public class CaseSearch {
  @SerializedName("slug")
  private String slug = null;

  @SerializedName("date")
  private LocalDate date = null;

  @SerializedName("court_jurisdiction")
  private String courtJurisdiction = null;

  @SerializedName("court_level_of_appeal")
  private String courtLevelOfAppeal = null;

  @SerializedName("decision_type")
  private String decisionType = null;

  @SerializedName("court")
  private String court = null;

  @SerializedName("text")
  private String text = null;

  @SerializedName("id")
  private String id = null;

  public CaseSearch slug(String slug) {
    this.slug = slug;
    return this;
  }

   /**
   * Used to urls (consists of court, date, file number)
   * @return slug
  **/
  @ApiModelProperty(required = true, value = "Used to urls (consists of court, date, file number)")
  public String getSlug() {
    return slug;
  }

  public void setSlug(String slug) {
    this.slug = slug;
  }

  public CaseSearch date(LocalDate date) {
    this.date = date;
    return this;
  }

   /**
   * Publication date as in source
   * @return date
  **/
  @ApiModelProperty(value = "Publication date as in source")
  public LocalDate getDate() {
    return date;
  }

  public void setDate(LocalDate date) {
    this.date = date;
  }

   /**
   * Get courtJurisdiction
   * @return courtJurisdiction
  **/
  @ApiModelProperty(value = "")
  public String getCourtJurisdiction() {
    return courtJurisdiction;
  }

   /**
   * Get courtLevelOfAppeal
   * @return courtLevelOfAppeal
  **/
  @ApiModelProperty(value = "")
  public String getCourtLevelOfAppeal() {
    return courtLevelOfAppeal;
  }

   /**
   * Get decisionType
   * @return decisionType
  **/
  @ApiModelProperty(value = "")
  public String getDecisionType() {
    return decisionType;
  }

  public CaseSearch court(String court) {
    this.court = court;
    return this;
  }

   /**
   * Responsible court entity
   * @return court
  **/
  @ApiModelProperty(value = "Responsible court entity")
  public String getCourt() {
    return court;
  }

  public void setCourt(String court) {
    this.court = court;
  }

  public CaseSearch text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  @ApiModelProperty(required = true, value = "")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaseSearch caseSearch = (CaseSearch) o;
    return Objects.equals(this.slug, caseSearch.slug) &&
        Objects.equals(this.date, caseSearch.date) &&
        Objects.equals(this.courtJurisdiction, caseSearch.courtJurisdiction) &&
        Objects.equals(this.courtLevelOfAppeal, caseSearch.courtLevelOfAppeal) &&
        Objects.equals(this.decisionType, caseSearch.decisionType) &&
        Objects.equals(this.court, caseSearch.court) &&
        Objects.equals(this.text, caseSearch.text) &&
        Objects.equals(this.id, caseSearch.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(slug, date, courtJurisdiction, courtLevelOfAppeal, decisionType, court, text, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaseSearch {\n");
    
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    courtJurisdiction: ").append(toIndentedString(courtJurisdiction)).append("\n");
    sb.append("    courtLevelOfAppeal: ").append(toIndentedString(courtLevelOfAppeal)).append("\n");
    sb.append("    decisionType: ").append(toIndentedString(decisionType)).append("\n");
    sb.append("    court: ").append(toIndentedString(court)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

