/*
 * Open Legal Data API
 * With the Open Legal Data API you can access various data from the legal domain, e.g. law text or case files. The data may be used for semantic analysis or to create statistics. For more information visit our website. https://openlegaldata.io/
 *
 * OpenAPI spec version: v1
 * Contact: hello@openlegaldata.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * CaseAnnotation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-18T15:11:46.584Z")
public class CaseAnnotation {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("belongs_to")
  private Integer belongsTo = null;

  @SerializedName("label")
  private Integer label = null;

  @SerializedName("value_str")
  private String valueStr = null;

  @SerializedName("value_int")
  private Integer valueInt = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  @SerializedName("updated_at")
  private OffsetDateTime updatedAt = null;

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public CaseAnnotation belongsTo(Integer belongsTo) {
    this.belongsTo = belongsTo;
    return this;
  }

   /**
   * Get belongsTo
   * @return belongsTo
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getBelongsTo() {
    return belongsTo;
  }

  public void setBelongsTo(Integer belongsTo) {
    this.belongsTo = belongsTo;
  }

  public CaseAnnotation label(Integer label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getLabel() {
    return label;
  }

  public void setLabel(Integer label) {
    this.label = label;
  }

  public CaseAnnotation valueStr(String valueStr) {
    this.valueStr = valueStr;
    return this;
  }

   /**
   * Get valueStr
   * @return valueStr
  **/
  @ApiModelProperty(value = "")
  public String getValueStr() {
    return valueStr;
  }

  public void setValueStr(String valueStr) {
    this.valueStr = valueStr;
  }

  public CaseAnnotation valueInt(Integer valueInt) {
    this.valueInt = valueInt;
    return this;
  }

   /**
   * Get valueInt
   * minimum: -2147483648
   * maximum: 2147483647
   * @return valueInt
  **/
  @ApiModelProperty(value = "")
  public Integer getValueInt() {
    return valueInt;
  }

  public void setValueInt(Integer valueInt) {
    this.valueInt = valueInt;
  }

   /**
   * Entry is created at this date time
   * @return createdAt
  **/
  @ApiModelProperty(value = "Entry is created at this date time")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

   /**
   * Date time of last change
   * @return updatedAt
  **/
  @ApiModelProperty(value = "Date time of last change")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaseAnnotation caseAnnotation = (CaseAnnotation) o;
    return Objects.equals(this.id, caseAnnotation.id) &&
        Objects.equals(this.belongsTo, caseAnnotation.belongsTo) &&
        Objects.equals(this.label, caseAnnotation.label) &&
        Objects.equals(this.valueStr, caseAnnotation.valueStr) &&
        Objects.equals(this.valueInt, caseAnnotation.valueInt) &&
        Objects.equals(this.createdAt, caseAnnotation.createdAt) &&
        Objects.equals(this.updatedAt, caseAnnotation.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, belongsTo, label, valueStr, valueInt, createdAt, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaseAnnotation {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    belongsTo: ").append(toIndentedString(belongsTo)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    valueStr: ").append(toIndentedString(valueStr)).append("\n");
    sb.append("    valueInt: ").append(toIndentedString(valueInt)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

