/*
 * Open Legal Data API
 * With the Open Legal Data API you can access various data from the legal domain, e.g. law text or case files. The data may be used for semantic analysis or to create statistics. For more information visit our website. https://openlegaldata.io/
 *
 * OpenAPI spec version: v1
 * Contact: hello@openlegaldata.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Court
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-18T15:11:46.584Z")
public class Court {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("court_type")
  private String courtType = null;

  @SerializedName("city")
  private Integer city = null;

  @SerializedName("state")
  private Integer state = null;

  @SerializedName("code")
  private String code = null;

  @SerializedName("slug")
  private String slug = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("image")
  private String image = null;

  @SerializedName("homepage")
  private String homepage = null;

  @SerializedName("street_address")
  private String streetAddress = null;

  @SerializedName("postal_code")
  private String postalCode = null;

  @SerializedName("address_locality")
  private String addressLocality = null;

  @SerializedName("telephone")
  private String telephone = null;

  @SerializedName("fax_number")
  private String faxNumber = null;

  @SerializedName("jurisdiction")
  private String jurisdiction = null;

  @SerializedName("level_of_appeal")
  private String levelOfAppeal = null;

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public Court name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Full name of the court with location
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Full name of the court with location")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Court courtType(String courtType) {
    this.courtType = courtType;
    return this;
  }

   /**
   * Court type AG,VG,...
   * @return courtType
  **/
  @ApiModelProperty(value = "Court type AG,VG,...")
  public String getCourtType() {
    return courtType;
  }

  public void setCourtType(String courtType) {
    this.courtType = courtType;
  }

  public Court city(Integer city) {
    this.city = city;
    return this;
  }

   /**
   * Court belongs to this city, if null court is state-level
   * @return city
  **/
  @ApiModelProperty(value = "Court belongs to this city, if null court is state-level")
  public Integer getCity() {
    return city;
  }

  public void setCity(Integer city) {
    this.city = city;
  }

  public Court state(Integer state) {
    this.state = state;
    return this;
  }

   /**
   * Court belongs to this state (derive country of this field)
   * @return state
  **/
  @ApiModelProperty(required = true, value = "Court belongs to this state (derive country of this field)")
  public Integer getState() {
    return state;
  }

  public void setState(Integer state) {
    this.state = state;
  }

  public Court code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Unique court identifier based on ECLI (e.g. BVerfG)
   * @return code
  **/
  @ApiModelProperty(required = true, value = "Unique court identifier based on ECLI (e.g. BVerfG)")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public Court slug(String slug) {
    this.slug = slug;
    return this;
  }

   /**
   * Type &amp; city name as lowercase
   * @return slug
  **/
  @ApiModelProperty(required = true, value = "Type & city name as lowercase")
  public String getSlug() {
    return slug;
  }

  public void setSlug(String slug) {
    this.slug = slug;
  }

  public Court description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

   /**
   * Get image
   * @return image
  **/
  @ApiModelProperty(value = "")
  public String getImage() {
    return image;
  }

  public Court homepage(String homepage) {
    this.homepage = homepage;
    return this;
  }

   /**
   * Official court homepage
   * @return homepage
  **/
  @ApiModelProperty(value = "Official court homepage")
  public String getHomepage() {
    return homepage;
  }

  public void setHomepage(String homepage) {
    this.homepage = homepage;
  }

  public Court streetAddress(String streetAddress) {
    this.streetAddress = streetAddress;
    return this;
  }

   /**
   * Street address with house number
   * @return streetAddress
  **/
  @ApiModelProperty(value = "Street address with house number")
  public String getStreetAddress() {
    return streetAddress;
  }

  public void setStreetAddress(String streetAddress) {
    this.streetAddress = streetAddress;
  }

  public Court postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Postal code (ZIP code)
   * @return postalCode
  **/
  @ApiModelProperty(value = "Postal code (ZIP code)")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public Court addressLocality(String addressLocality) {
    this.addressLocality = addressLocality;
    return this;
  }

   /**
   * Locality (city name)
   * @return addressLocality
  **/
  @ApiModelProperty(value = "Locality (city name)")
  public String getAddressLocality() {
    return addressLocality;
  }

  public void setAddressLocality(String addressLocality) {
    this.addressLocality = addressLocality;
  }

  public Court telephone(String telephone) {
    this.telephone = telephone;
    return this;
  }

   /**
   * Telephone number
   * @return telephone
  **/
  @ApiModelProperty(value = "Telephone number")
  public String getTelephone() {
    return telephone;
  }

  public void setTelephone(String telephone) {
    this.telephone = telephone;
  }

  public Court faxNumber(String faxNumber) {
    this.faxNumber = faxNumber;
    return this;
  }

   /**
   * Fax number
   * @return faxNumber
  **/
  @ApiModelProperty(value = "Fax number")
  public String getFaxNumber() {
    return faxNumber;
  }

  public void setFaxNumber(String faxNumber) {
    this.faxNumber = faxNumber;
  }

  public Court jurisdiction(String jurisdiction) {
    this.jurisdiction = jurisdiction;
    return this;
  }

   /**
   * Jurisdiction of court (ordinary, civil, ...)
   * @return jurisdiction
  **/
  @ApiModelProperty(value = "Jurisdiction of court (ordinary, civil, ...)")
  public String getJurisdiction() {
    return jurisdiction;
  }

  public void setJurisdiction(String jurisdiction) {
    this.jurisdiction = jurisdiction;
  }

  public Court levelOfAppeal(String levelOfAppeal) {
    this.levelOfAppeal = levelOfAppeal;
    return this;
  }

   /**
   * Subject-matter jurisdiction (local, federal, high court, ...)
   * @return levelOfAppeal
  **/
  @ApiModelProperty(value = "Subject-matter jurisdiction (local, federal, high court, ...)")
  public String getLevelOfAppeal() {
    return levelOfAppeal;
  }

  public void setLevelOfAppeal(String levelOfAppeal) {
    this.levelOfAppeal = levelOfAppeal;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Court court = (Court) o;
    return Objects.equals(this.id, court.id) &&
        Objects.equals(this.name, court.name) &&
        Objects.equals(this.courtType, court.courtType) &&
        Objects.equals(this.city, court.city) &&
        Objects.equals(this.state, court.state) &&
        Objects.equals(this.code, court.code) &&
        Objects.equals(this.slug, court.slug) &&
        Objects.equals(this.description, court.description) &&
        Objects.equals(this.image, court.image) &&
        Objects.equals(this.homepage, court.homepage) &&
        Objects.equals(this.streetAddress, court.streetAddress) &&
        Objects.equals(this.postalCode, court.postalCode) &&
        Objects.equals(this.addressLocality, court.addressLocality) &&
        Objects.equals(this.telephone, court.telephone) &&
        Objects.equals(this.faxNumber, court.faxNumber) &&
        Objects.equals(this.jurisdiction, court.jurisdiction) &&
        Objects.equals(this.levelOfAppeal, court.levelOfAppeal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, courtType, city, state, code, slug, description, image, homepage, streetAddress, postalCode, addressLocality, telephone, faxNumber, jurisdiction, levelOfAppeal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Court {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    courtType: ").append(toIndentedString(courtType)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    homepage: ").append(toIndentedString(homepage)).append("\n");
    sb.append("    streetAddress: ").append(toIndentedString(streetAddress)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    addressLocality: ").append(toIndentedString(addressLocality)).append("\n");
    sb.append("    telephone: ").append(toIndentedString(telephone)).append("\n");
    sb.append("    faxNumber: ").append(toIndentedString(faxNumber)).append("\n");
    sb.append("    jurisdiction: ").append(toIndentedString(jurisdiction)).append("\n");
    sb.append("    levelOfAppeal: ").append(toIndentedString(levelOfAppeal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

