/*
 * Open Legal Data API
 * With the Open Legal Data API you can access various data from the legal domain, e.g. law text or case files. The data may be used for semantic analysis or to create statistics. For more information visit our website. https://openlegaldata.io/
 *
 * OpenAPI spec version: v1
 * Contact: hello@openlegaldata.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import java.math.BigDecimal;
import io.swagger.client.model.CaseAnnotation;
import io.swagger.client.model.InlineResponse2001;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CaseAnnotationsApi
 */
@Ignore
public class CaseAnnotationsApiTest {

    private final CaseAnnotationsApi api = new CaseAnnotationsApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void caseAnnotationsCreateTest() throws ApiException {
        CaseAnnotation data = null;
        CaseAnnotation response = api.caseAnnotationsCreate(data);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void caseAnnotationsDeleteTest() throws ApiException {
        Integer id = null;
        api.caseAnnotationsDelete(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void caseAnnotationsListTest() throws ApiException {
        BigDecimal belongsTo = null;
        BigDecimal label = null;
        Integer limit = null;
        Integer offset = null;
        InlineResponse2001 response = api.caseAnnotationsList(belongsTo, label, limit, offset);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void caseAnnotationsPartialUpdateTest() throws ApiException {
        Integer id = null;
        CaseAnnotation data = null;
        CaseAnnotation response = api.caseAnnotationsPartialUpdate(id, data);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void caseAnnotationsReadTest() throws ApiException {
        Integer id = null;
        CaseAnnotation response = api.caseAnnotationsRead(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void caseAnnotationsUpdateTest() throws ApiException {
        Integer id = null;
        CaseAnnotation data = null;
        CaseAnnotation response = api.caseAnnotationsUpdate(id, data);

        // TODO: test validations
    }
    
}
