/*
 * Open Legal Data API
 * With the Open Legal Data API you can access various data from the legal domain, e.g. law text or case files. The data may be used for semantic analysis or to create statistics. For more information visit our website. https://openlegaldata.io/
 *
 * OpenAPI spec version: v1
 * Contact: hello@openlegaldata.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse2008;
import io.swagger.client.model.LawBook;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LawBooksApi
 */
@Ignore
public class LawBooksApiTest {

    private final LawBooksApi api = new LawBooksApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void lawBooksCreateTest() throws ApiException {
        LawBook data = null;
        LawBook response = api.lawBooksCreate(data);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void lawBooksDeleteTest() throws ApiException {
        Integer id = null;
        api.lawBooksDelete(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void lawBooksListTest() throws ApiException {
        String slug = null;
        String code = null;
        String latest = null;
        String revisionDate = null;
        Integer limit = null;
        Integer offset = null;
        InlineResponse2008 response = api.lawBooksList(slug, code, latest, revisionDate, limit, offset);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void lawBooksPartialUpdateTest() throws ApiException {
        Integer id = null;
        LawBook data = null;
        LawBook response = api.lawBooksPartialUpdate(id, data);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void lawBooksReadTest() throws ApiException {
        Integer id = null;
        LawBook response = api.lawBooksRead(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void lawBooksUpdateTest() throws ApiException {
        Integer id = null;
        LawBook data = null;
        LawBook response = api.lawBooksUpdate(id, data);

        // TODO: test validations
    }
    
}
