/*
 * Open Legal Data API
 * With the Open Legal Data API you can access various data from the legal domain, e.g. law text or case files. The data may be used for semantic analysis or to create statistics. For more information visit our website. https://openlegaldata.io/
 *
 * OpenAPI spec version: v1
 * Contact: hello@openlegaldata.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse20012;
import io.swagger.client.model.User;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Ignore
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    
    /**
     * 
     *
     * API endpoint that allows a user&#39;s profile to be viewed or edited.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usersListTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        InlineResponse20012 response = api.usersList(limit, offset);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Show current user (useful for verifying API key)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usersMeTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        InlineResponse20012 response = api.usersMe(limit, offset);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * API endpoint that allows a user&#39;s profile to be viewed or edited.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usersReadTest() throws ApiException {
        Integer id = null;
        User response = api.usersRead(id);

        // TODO: test validations
    }
    
}
